version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rdok-openapi-showcase"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gls3cd4hrabc"
s3_prefix = "rdok-openapi-showcase"
region = "eu-west-1"
profile = "rdok"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
