openapi: 3.0.0
info:
  title: hello-world
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: Local
  - description: AWS-SAM
    url: '${HelloWorldApi}'
paths:
  /hello-world-v2:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-hello-world
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                inline-model:
                  $ref: '#/components/schemas/Message'
                external-model:
                  $ref: ./user.v1.yaml
      x-amazon-apigateway-integration:
        uri:
          'Fn::Sub': 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
components:
  schemas:
    Message:
      title: Message
      type: object
      properties:
        message:
          type: string
