openapi: 3.0.0
info:
  title: hello-world
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: Local
  - description: AWS-SAM
    url: '${HelloWorldApi}'
paths:
  /hello-world:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-hello-world
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
components:
  schemas:
    Message:
      title: Message
      type: object
      properties:
        message:
          type: string
